baseurl = "https://zainimran.com/"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Zain Imran"
title = "Zain Imran"
googleAnalytics = "UA-115861944-1"
disqusshortname = ""
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Zain's website"
# copyright = "Copyright © 2017 Zain Imran"
# copyrightUrl = "https://creativecommons.org/licenses/by-sa/4.0/"
logofile = "img/profile_photo-2.jpg"
faviconfile = "img/favicon.png"
highlightjs = true
# progressively = true
share = true
latestpostcount = 5
# github = "zainimran"
email = "zainimran@outlook.com"
linkedin = "zainimran17"
# twitter = "example"
facebook = "zainimran17"
social_banner = "img/banner.png"
usesmallsummarycard = true
posts_navigation = true
# issoHost = "comments.domain.tld:1234"
# githubRepo = "githubUsername/repositoryName"
small_banner_logo = false

[params.colors]
identifier = "#527fc1f"
identifier_dark = "#1a3152"
trivial = "#6a7a8b"
foreground = "#181d2a"
background = "#f9f9f9"
background_dark = "#282a36"
code = "#87a5d2"
type = "#97d28b"
special = "#ffcb8d"
value = "#96c2d7"
statement = "#ff8e91"